

const Content = (props) => (

  <div className="{styles.container}">
  <Head>
    <title>Associação dos Ambulantes</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
 
  <main className={styles.main}>
 
 
 
 <Image src="/images/logotip.png" alt="Logo AAMD" width={200} height={200} />
 
    <h2 className={styles.title}>
    Sejam bem vindos ao nosso site
    </h2>
 
    <p className={styles.description}>
      Estamos auxiliando os Ambulantes com informações importantes
    </p>
 
 
 <Image src="/images/assoc.jpg" alt="Logo AAMD" width={500} height={200} />
 
    <p className={styles.description}>
    Associação é uma organização resultante da reunião legal entre duas 
    ou até mais pessoas, com ou sem personalidade jurídica, para a realização de um objetivo comum.
 </p>
 
    <p className={styles.description}>
     Associação e seus Direitos
   
    </p>
 
    <div className={styles.grid}>
      <a href="https://nextjs.org/docs" className={styles.card}>
        <h2>Constituição Federal</h2>
        <p> 
          “Todos são iguais perante a lei, sem distinção de qualquer natureza, 
          garantindo-se aos brasileiros e aos estrangeiros residentes no País a 
          inviolabilidade do direito à vida, à liberdade, à igualdade, à segurança 
          e à propriedade”.</p>
      </a>
 
 
  
 
      <a href="https://nextjs.org/learn" className={styles.card}>
      <p>
      <h2>Liberdade de associação</h2>
      A liberdade de associação é garantida no inciso XVII do Artigo 5º da Constituição, 
      que determina que somos livres para criar ou participar de associações desde que 
      seus fins sejam lícitos e que não tenham caráter paramilitar.
 
      </p>
      </a>
 
      <a
        href="https://github.com/vercel/next.js/tree/master/examples"
        className={styles.card}
      >
        <h2>Constituição Federal &rarr;</h2>
 
 
 
        <p>
 
        INCISO XVIII – LIVRE CONSTITUIÇÃO DE ASSOCIAÇÕES
 “A criação de associações e, na forma da lei, a de cooperativas independem 
 de autorização, sendo vedada a interferência estatal em seu funcionamento”
        </p>
 
 
 
      </a>
 
      <a
        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        className={styles.card}
      >
        <h2>Deploy &rarr;</h2>
        <p>
          Instantly deploy your Next.js site to a public URL with Vercel.
        </p>
      </a>
    </div>
  </main>
 
  <footer className={styles.footer}>
    <a
      href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
      target="_blank"
      rel="noopener noreferrer"
    >
      Powered by{' '}
      <span className={styles.logo}>
        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
      </span>
    </a>
  </footer>
 </div>
)

export default Content