const HeadLayout = (props) => (

   <div>
  

  <title>Associação dos Ambulantes</title>
   <meta name="description" content="Generated by create next app" />
   <link rel="icon" href="/favicon.ico" />
   <meta name="viewport" content="width=device-width, initial-scale=1.0"/>


   <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet"/>

<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"/>


     


        </div>

    )

export default HeadLayout